// Feather disable all

#macro LATTICE_VERSION  "0.0.0"
#macro LATTICE_DATE     "2024-10-31"

#macro LATTICE_SYMBOLS_WIDTH   (floor(LATTICE_SYMBOL_TEXTURE_WIDTH/LATTICE_CELL_WIDTH))
#macro LATTICE_SYMBOLS_HEIGHT  (floor(LATTICE_SYMBOL_TEXTURE_HEIGHT/LATTICE_CELL_HEIGHT))
#macro LATTICE_TOTAL_SYMBOLS   (LATTICE_SYMBOLS_WIDTH*LATTICE_SYMBOLS_HEIGHT - 1)