// Feather disable all

#macro LATTICE_COLUMNS  80
#macro LATTICE_ROWS     30

#macro LATTICE_CELL_WIDTH    8
#macro LATTICE_CELL_HEIGHT  16

#macro LATTICE_SYMBOL_TEXTURE_WIDTH   512
#macro LATTICE_SYMBOL_TEXTURE_HEIGHT  512